### ISSUE TITLE
Is it okay to add value mapping support using unofficial Value mapping APIs

### ISSUE THREAD

**Issue by Srinu3366** [engswee/flashpipe#1]
I am working on enhancing the code to support value mapping. Are you okay with using unofficial Value mapping APIs to support PUT operation?

Thanks,
Srini

**Comment by engswee** [comment]
Hi Srini

First of all, really glad to know that your pipeline is up and running with FlashPipe.

It’s great to know that you are looking to contribute as well 😉

Regarding unofficial APIs, I would like to discuss further on this. The key point is as much as possible I would like to make sure it works on both Neo and Cloud Foundry. If that is not the case here, then we will have to brainstorm further what’s the best approach to include such limited/conditional functionality.

Can you provide more details here on the unofficial API that you are considering for the PUT operation?

One last (administrative) point - please do read up the contributing guidelines before making your first commit. There is an automated check on all commits in Pull Requests. If you have any questions on that, let me know

**Comment by Srinu3366** [comment]
POST /ValueMappingDesigntimeArtifacts - Create new value maps
POST /DeployValueMappingDesigntimeArtifact?Id='{Id}'&Version='{Version}' - Deploy a value map
PUT /itspaces/api/1.0/workspace/<package id>/artifacts/<mapping id>/entities/<mapping id>/valuemappings/<mapping id>

https://int4.com/sap-cpi-value-mapping-maintenance - This blog has details about updating value mappings. It is a cumbersome process to lock first and then upload the content but don't see any other options right now. But I think value mappings support complements the capabilities of this tool. 

I don't have access to a CF tenant right now. I hope the workspace API is the same for CF and Neo. Otherwise, we can introduce a parameter to specify the runtime.

Don't have any questions about the contributing guidelines.

Thanks,
Srini

**Comment by engswee** [comment]
Hi Srini,

As adding value mapping support may take some effort, I have created a different branch called "**value_mapping**" so that we can collaborate on it before it makes it into a Docker image release.
Please start your work from that branch and also create pull requests on that branch instead of the main branch.

Regarding update of existing value map, can you also please check if the POST /UpsertValMaps would be able to handle both create and update?
https://api.sap.com/api/IntegrationContent/resource
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/7220623/120700186-a3207180-c4b1-11eb-97fa-f3347f70af17.png">

I have access to both CF and Neo, so once your changes are in, I can test them out on both.

**Comment by Srinu3366** [comment]
/UpsertValMaps is able to handle create fine but it can't update. For updates, it creates another entry with new keys. We can handle this by setting up default values for a Map so that it returns the expected value.

**Comment by engswee** [comment]
Ok, thanks for the update. Let's give the approach you mention a try then.

**Comment by engswee** [comment]
I'm closing this issue as there is no progress here. Additionally, without a public API to update Value Mappings available at the moment, including support for value mapping will be incomplete, i.e. it is not possible to fully automate the process, therefore the value proposition is low.
