### ISSUE TITLE
Value mapping, Script Collection and Integration adapter artifacts Sync

### ISSUE THREAD

**Issue by BoopathiRamasamy** [engswee/flashpipe#34]
Hi @engswee ,

Please let us know, will github flash pipeline supports Value mapping, Script collection and Integration adapter syncing into Github and movement to test tenant.

Thanks
Boopathi

**Comment by engswee** [comment]
Yes, flashpipe v3.0.0 onwards supports Value Mapping, Script Collection and Message Mapping as well. 
https://equaliseit.com/go-go-flashpipe-major-version-v3-0-0-release/

Integration Adapter is not supported because the public API released by SAP does not have download functionality.

`sync` command automatically handles the different types, while `update` and `deploy` requires you to specify the `artifact-type`
You can check out examples in https://github.com/engswee/flashpipe-demo
